languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "personalized"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://rajivranjan-singh.in/"
title = "Rajivranjan Singh"
#googleAnalytics = ""


